# Generated by Django 3.1.3 on 2021-01-01 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shippingorder',
            new_name='shippingaddress',
        ),
    ]
