# Generated by Django 3.1.3 on 2020-12-20 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_auto_20201220_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='customer',
        ),
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='customer',
        ),
    ]
