# Generated by Django 3.1.3 on 2020-12-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_profile_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cv',
        ),
    ]
